# Generated by Django 4.2 on 2024-03-22 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_products_delete_product_store_store_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_timestamp',
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_timestamp',
        ),
    ]
